<?php

namespace CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function searchFriends($keysecure, $val)
    {
        $qb = $this->createQueryBuilder('user');
        $qb
            ->addSelect('user.name')
            ->addSelect('user.id')
            ->addSelect('user.key_avatar')
            ->where('user.email LIKE :val')
            ->orWhere('user.name LIKE :val')
            ->andWhere('user.key_secure != :keysecure')
            ->setParameter('val', $val.'%')
            ->setParameter('keysecure', $keysecure);
        return $qb
            ->getQuery()
            ->getArrayResult();
    }
}
