common:
    resource: "@CommonBundle/Resources/config/routing.yml"
    prefix:   /

calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
